#!/usr/bin/env bash
# shellcheck disable=SC2086

# Define a function to query DNS information for a subdomain
query_subdomain() {
    local subdomain="$1"
    local domain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}'
}

# Check the number of arguments
args="$#"
if [[ "$args" -eq 1 ]]; then
    # Call the function for each subdomain
    query_subdomain www "$1"
    query_subdomain lb-01 "$1"
    query_subdomain web-01 "$1"
    query_subdomain web-02 "$1"
elif [[ "$args" -eq 2 ]]; then
	# call the function for the particular subdomain
	domain="$1"
	subdomain="$2"
    
	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}'
else
	exit 1
fi
