#!/usr/bin/env bash
# Installing Nginx Web Server and Serving HTML page

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello world!" | sudo tee /var/www/html/index.nginx-debian.html

sudo /etc/init.d/nginx reload

sudo apt-get install curl

curl localhost
