#!/usr/bin/env bash
# Installing Nginx Web Server and Serving HTML page

apt-get update -y

apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

/etc/init.d/nginx reload

apt-get install curl

curl localhost
