#!/usr/bin/env bash
# Installing Nginx Web Server and Serving HTML page

apt-get update

apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

service nginx reload
