#!/usr/bin/env bash
#configure Nginx server to redirect to another page
#!/usr/bin/env bash
# automate installation and set up of nginx web server, redirection
# and custom error messages

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

replace_str="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com;\n\t}"

sudo sed -i "s/server_name _;/$replace_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
