#!/usr/bin/env bash
#configure Nginx server to redirect to another page

sudo apt-get -y update

sudo apt-get -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replace_str="server_name _;\n\tlocation ^\/redirect_me {\n\t return 301 https:\/\/www.google.com;\n\t"

sudo sed -i "s/server_name _;/$replace_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
