#!/usr/bin/env bash
#configure Nginx server to redirect to another page

sudo apt-get -y update

sudo apt-get -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"

sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
