#!/usr/bin/env bash
# transfer a file from client to server

args="$#"
if [[ $args -lt 3 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path="$1"
	ip_addr="$2"
	usr="$3"
	ssh_key_path="$4"
	scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$usr"@"$ip_addr":~/
fi
