#!/usr/bin/env bash
# Install and configures HAproxy on my lb-01 server

# Update system packages
sudo apt-get update -y

# install HAProxy
apt-get install haproxy -y

# change server configuration

config=\
"
frontend benehub-frontend
	bind *:80
	mode http
	default_backend benehub-backend
backend benehub-backend
	mode http
	balance roundrobin
	server 295751-web-01 18.208.120.245:80 check
	server 295751-web-02 34.204.60.174:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by the init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
