#!/usr/bin/env bash
# This script prints FizzBuzz, Fizz and Buzz
i=1
while [[ i -le 100 ]]
do
	div_3=$((i % 3))
	div_5=$((i % 5))

	if [[ $div_3 == 0 && $div_5 == 0 ]]
	then
		echo "FizzBuzz"

	elif [[ $div_3 == 0 ]]
	then
		echo "Fizz"

	elif [[ $div_5 == 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi

	(( i++ ))
done
