#!/usr/bin/env bash
# script displays the content of the file /etc/passwd
file=/etc/passwd
exec < $file
while IFS=: read -r username password uid gid info home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"

done < "$file"
