#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [[ i -le 20 ]]
do
	if [ $i == 4 ]
	then
		echo "$i"
		echo "bad luck from China"

	elif [ $i == 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"

	elif [ $i == 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"

	else
		echo "$i"
	fi

	(( i+= 1 ))
done
